// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5CthGrBqW84rDLBNNSkGkYeCKjPF_3IY',
    appId: '1:11016859741:web:29d0c05e31b64271125db4',
    messagingSenderId: '11016859741',
    projectId: 'flutter-eventgo',
    authDomain: 'flutter-eventgo.firebaseapp.com',
    storageBucket: 'flutter-eventgo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_7-Y5DZDSD0tUZYvx-W1JY0fBxU_F3gY',
    appId: '1:11016859741:android:0a5931901c0b7935125db4',
    messagingSenderId: '11016859741',
    projectId: 'flutter-eventgo',
    storageBucket: 'flutter-eventgo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8rJxS9FI3YfJqXsGKDe4Oc3FGGNlXqgk',
    appId: '1:11016859741:ios:1ea97a31c115ac40125db4',
    messagingSenderId: '11016859741',
    projectId: 'flutter-eventgo',
    storageBucket: 'flutter-eventgo.appspot.com',
    iosClientId: '11016859741-m5m7c0c1mn1vbnrm8bf0tmidu8v4oc9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventgo',
  );
}
